### ISSUE TITLE
Help command doesn't work 

### ISSUE THREAD

**Issue by aszenz** [theofidry/PsyshBundle#60]
The symfony output interface lacks the page method which breaks the help command, need to use ShellOutput
```
<aside>Psy Shell v0.10.6 (PHP 7.4.12 — cli) by Justin Hileman</aside>
>>> help ls
PHP Error:  Call to undefined method Symfony\Component\Console\Output\ConsoleOutput::page() in /var/www/app-bi/vendor/psy/psysh/src/Command/HelpCommand.php on line 65
```
Tested on symfony 5.2 and 4.4

**Comment by aszenz** [comment]
I'm not sure if this needs to go into https://github.com/bobthecow/psysh or this, the interface https://github.com/symfony/console/blob/5.x/Output/OutputInterface.php doesn't have the method page

**Comment by dvthjkr** [comment]
> I'm not sure if this needs to go into https://github.com/bobthecow/psysh or this, the interface https://github.com/symfony/console/blob/5.x/Output/OutputInterface.php doesn't have the method page

See : https://github.com/theofidry/PsyshBundle/issues/57#issuecomment-771787338

Actually, part of the problem can be solved here. My best solution was to add : 
```
        if (!$output instanceof ShellOutput) {
            $output = null;
        }
```
at the beginning of the execute method of PsyshCommand (/vendor/theofidry/psysh-bundle/src/Command/PsyshCommand.php:42)

this solves the "help ls" problem. 

But the issue is more complicated than that. because if you try to run a non-existing command, it issues a warning message that is not formatted : 

`<warning>PHP Warning:  Use of undefined constant test - assumed 'test' (this will throw an Error in a future version of PHP) in D:\src\dv-appeval()'d code on line 1</warning>`

Actually, when it comes to "write" some message to the "Output", either a "ShellOutput" is used, or a "StreamOutput", I did not exactly figure out why one or the other, but when the StreamOutput is used, its OutputFormatter is set with less styles (4 vs 25 for a ShellOutput instance). 
=> and this is psy/psysh code.

**Comment by palibodatanja** [comment]
@aszenz

**Comment by palibodatanja** [comment]
![IMG_20230315_023620_233.png](https://user-images.githubusercontent.com/79591672/225297983-b7b2df0a-0459-4268-b6bb-cdf325ea68b4.png)

**Comment by palibodatanja** [comment]
- ****
